#  Authors: Rourke750, ibbignerd
#  Last updated on 06/15/13
#  This plugin was designed for use by Civcraft
# 
#  garblevariation: the range added to the garble to make it more random
#  defaultcolor: Default color of chat. Must use a ChatColor.COLOR option
#  greyscale: as the reciever is farther away, the chat changes colors
#  yvariation: The higher you are, the farther you can talk.
#      maxrange += yvariation amount * y of sender;
#  yvariation amount: Multiplier amount of above
#  range distance: amount subtracted from maxrange
# 
#  Below 0 range is no garble
#  range garble: amount as a whole percent that the text should be garbled
#  range color: if greyscale is true, color of chat based on range
#  maxrange: distance a player can be heard
chat:
  variation: 5
  defaultcolor: WHITE
  greyscale: false
  yvariation:
    enabled: true
    noGarbLevel: 70
  shout:
    enabled: true
    char: '!'
    distanceAdded: 100
    hungerreduced: 2
  whisper:
    enabled: true
    char: '#'
    distance: 50
    color: WHITE
  range:
    '0':
      distance: 500
      garble: 5
      color: GRAY
    '1':
      distance: 350
      garble: 15
      color: GRAY
    '2':
      distance: 200
      garble: 35
      color: DARK_GRAY
    maxrange: 1000
