name: CivChat
main: com.untamedears.civchat.CivChat
version: .4
author: Rourke750
commands:
   tell:
      description: Sends a player a message.
      usage: /<command> <player2 name> <Message>
      aliases: message
   civchat:
      description: sets reload or save command.
      usage: /<command> <arg1>
      permission: civchat.admin
permissions:
   civchat.admin:
      description: Admin commands for civchat.
      default: op