name: CivChat

main: com.untamedears.civchat.CivChat

version: .81

author: Rourke750, ibbignerd

commands:

   tell:

      description: Sends a player a message.

      usage: /<command> <player> <message>

      aliases: message, msg, m

   exit:

      description: Exits personal message channel with player.

      usage: /exit

   civchat:

      description: Command for loading/saving config.

      usage: /<command> <subcommand>

      permission: civchat.admin

   groupchat:
      description: Command for talking to Citadel Groups.
      usage: /<command> <group> <message>
permissions:

   civchat.admin:

      description: Admin commands for civchat.

      default: op
